// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD94YvoW746UAJ_5fFR50Tl8fhLe1s_kA',
    appId: '1:948697541335:web:b54f10f9304e4f40e89e92',
    messagingSenderId: '948697541335',
    projectId: 'smart-pantry-app-99',
    authDomain: 'smart-pantry-app-99.firebaseapp.com',
    storageBucket: 'smart-pantry-app-99.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQCe4QKRbLpIog5xo016T2176eHg-xkxY',
    appId: '1:948697541335:android:9037b80aa2b8ccd3e89e92',
    messagingSenderId: '948697541335',
    projectId: 'smart-pantry-app-99',
    storageBucket: 'smart-pantry-app-99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBHouWeax-a_9ObE1510orNFijzJn4Q7c',
    appId: '1:948697541335:ios:7e9c2b116dcb123fe89e92',
    messagingSenderId: '948697541335',
    projectId: 'smart-pantry-app-99',
    storageBucket: 'smart-pantry-app-99.firebasestorage.app',
    iosBundleId: 'com.example.smartPantryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBHouWeax-a_9ObE1510orNFijzJn4Q7c',
    appId: '1:948697541335:ios:7e9c2b116dcb123fe89e92',
    messagingSenderId: '948697541335',
    projectId: 'smart-pantry-app-99',
    storageBucket: 'smart-pantry-app-99.firebasestorage.app',
    iosBundleId: 'com.example.smartPantryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD94YvoW746UAJ_5fFR50Tl8fhLe1s_kA',
    appId: '1:948697541335:web:e19fd69c08322bf2e89e92',
    messagingSenderId: '948697541335',
    projectId: 'smart-pantry-app-99',
    authDomain: 'smart-pantry-app-99.firebaseapp.com',
    storageBucket: 'smart-pantry-app-99.firebasestorage.app',
  );
}