name: smart_pantry_app
description: "Gestión inteligente de despensa con Firebase y Hive."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Gestión de archivos y compartir
  file_picker: ^8.1.2  # Para seleccionar el archivo JSON desde el móvil
  share_plus: ^10.1.4   # Para exportar el JSON (permite enviarlo por WhatsApp, Drive, etc.)
  
  # Backend & Auth
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  
  # Local Database (Offline)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0
  http: ^1.6.0
  mobile_scanner: ^7.1.4
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  flutter_native_splash: ^2.4.0
  cloud_firestore: ^5.6.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generators
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  
  # Asset Generators
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

# ---------------------------------------------------------
# Configuración de Iconos de la App (Escritorio)
# ---------------------------------------------------------
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_pantry.png"
  adaptive_icon_background: "#00A67E"
  adaptive_icon_foreground: "assets/images/icon_pantry.png"

# ---------------------------------------------------------
# Configuración del Splash Screen Nativo
# ---------------------------------------------------------
flutter_native_splash:
  color: "#00A67E"
  image: "assets/images/icon_pantry.png"
  android_12:
    image: "assets/images/icon_pantry.png"
    color: "#00A67E"
  fullscreen: true

flutter:
  uses-material-design: true

  # Registro de carpetas de recursos
  assets:
    - assets/images/